version: "3"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "9394:80"
    links:
      - phpfpm
    volumes:
      - ./app:/usr/share/nginx/html

      - ./nginx/etc/default.conf:/etc/nginx/conf.d/default.conf:ro

      - ./nginx/logs/error.log:/var/log/nginx/error.log

      - ./nginx/logs/access.log:/var/log/nginx/access.log

  phpfpm:
    build:
      context: ./php-fpm
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - ./app:/usr/share/nginx/html
    environment:
      - "DB_HOST=${DB_HOST}"

      - "DB_PORT=${DB_PORT}"

  mysql:
    build:
      context: ./mysql
    ports:
      - "3307:${DB_PORT}"
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"

      - "MYSQL_USER=${DB_USERNAME}"

      - "MYSQL_PASSWORD=${DB_PASSWORD}"

      - "MYSQL_DATABASE=${DB_DATABASE}"
    volumes:
      - ./mysql/data:/var/lib/mysql